"""doc in session

Revision ID: 2878fba7d0b8
Revises: 76d98faaeec1
Create Date: 2024-10-10 04:36:58.174386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2878fba7d0b8'
down_revision: Union[str, None] = '76d98faaeec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('aid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('function_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('vector_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['agent'], ['agents.agid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actions')
    # ### end Alembic commands ###
