"""title field in chat_sessions none

Revision ID: 4feeb331e915
Revises: f6f2f8b854af
Create Date: 2024-09-17 01:11:34.788129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4feeb331e915'
down_revision: Union[str, None] = 'f6f2f8b854af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
