"""action vector id

Revision ID: 8d4a71a1c2bb
Revises: 95b93c8d89fc
Create Date: 2024-10-07 18:11:01.992367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4a71a1c2bb'
down_revision: Union[str, None] = '95b93c8d89fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('vector_ids', sa.JSON(), nullable=True))
    op.alter_column('users', 'emailVerified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'emailVerified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('actions', 'vector_ids')
    # ### end Alembic commands ###
