"""user and limit

Revision ID: 95b93c8d89fc
Revises: 963cfd743d09
Create Date: 2024-09-19 21:55:33.471066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b93c8d89fc'
down_revision: Union[str, None] = '963cfd743d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('displayName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emailVerified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('photoURL', sa.String(), nullable=True))
    op.add_column('users', sa.Column('available_limits', sa.Numeric(), nullable=True))
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'available_limits')
    op.drop_column('users', 'photoURL')
    op.drop_column('users', 'emailVerified')
    op.drop_column('users', 'displayName')
    # ### end Alembic commands ###
