"""agent allowed_users update 

Revision ID: bc627d9d741c
Revises: bbdfa8a17c23
Create Date: 2024-09-15 12:27:57.560603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc627d9d741c'
down_revision: Union[str, None] = 'bbdfa8a17c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('allowed_users', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'allowed_users')
    # ### end Alembic commands ###
