"""initial models

Revision ID: c02966b9050e
Revises: 
Create Date: 2024-09-15 12:02:41.253976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02966b9050e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('access', sa.Enum('PUBLIC', 'PRIVATE', name='accesslevel'), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('agid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('actions',
    sa.Column('aid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('function_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['agent'], ['agents.agid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('agent_user_association',
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agid'], )
    )
    op.create_table('chat_sessions',
    sa.Column('sid', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['agent'], ['agents.agid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('knowledge_document',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('vector_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['agent'], ['agents.agid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_document')
    op.drop_table('chat_sessions')
    op.drop_table('agent_user_association')
    op.drop_table('actions')
    op.drop_table('agents')
    # ### end Alembic commands ###
